<?php

namespace AppBundle;

class CountryUtils {

	static private $countries_ = array(
		'AF' => array('Afghanistan'),
		'AL' => array('Albania'),
		'DZ' => array('Algeria'),
		'AS' => array('American Samoa'),
		'AD' => array('Andorra'),
		'AO' => array('Angola'),
		'AI' => array('Anguilla'),
		'AQ' => array('Antarctica'),
		'AG' => array('Antigua and Barbuda'),
		'AR' => array('Argentina'),
		'AM' => array('Armenia'),
		'AW' => array('Aruba'),
		'AU' => array('Australia'),
		'AT' => array('Austria'),
		'AZ' => array('Azerbaijan'),
		'BS' => array('Bahamas'),
		'BH' => array('Bahrain'),
		'BD' => array('Bangladesh'),
		'BB' => array('Barbados'),
		'BY' => array('Belarus'),
		'BE' => array('Belgium'),
		'BZ' => array('Belize'),
		'BJ' => array('Benin'),
		'BM' => array('Bermuda'),
		'BT' => array('Bhutan'),
		'BO' => array('Bolivia'),
		'BA' => array('Bosnia and Herzegovina'),
		'BW' => array('Botswana'),
		'BV' => array('Bouvet Island'),
		'BR' => array('Brazil'),
		'IO' => array('British Indian Ocean Territory'),
		'BN' => array('Brunei Darussalam'),
		'BG' => array('Bulgaria'),
		'BF' => array('Burkina Faso'),
		'BI' => array('Burundi'),
		'KH' => array('Cambodia'),
		'CM' => array('Cameroon'),
		'CA' => array('Canada'),
		'CV' => array('Cape Verde'),
		'KY' => array('Cayman Islands'),
		'CF' => array('Central African Republic'),
		'TD' => array('Chad'),
		'CL' => array('Chile'),
		'CN' => array('China'),
		'CX' => array('Christmas Island'),
		'CC' => array('Cocos (Keeling) Islands'),
		'CO' => array('Colombia'),
		'KM' => array('Comoros'),
		'CG' => array('Congo'),
		'CD' => array('Congo, the Democratic Republic of the'),
		'CK' => array('Cook Islands'),
		'CR' => array('Costa Rica'),
		'CI' => array('Cote d\'Ivoire'),
		'HR' => array('Croatia'),
		'CU' => array('Cuba'),
		'CY' => array('Cyprus'),
		'CZ' => array('Czech Republic'),
		'DK' => array('Denmark'),
		'DJ' => array('Djibouti'),
		'DM' => array('Dominica'),
		'DO' => array('Dominican Republic'),
		'EC' => array('Ecuador'),
		'EG' => array('Egypt'),
		'SV' => array('El Salvador'),
		'GQ' => array('Equatorial Guinea'),
		'ER' => array('Eritrea'),
		'EE' => array('Estonia'),
		'ET' => array('Ethiopia'),
		'FK' => array('Falkland Islands (Malvinas)'),
		'FO' => array('Faroe Islands'),
		'FJ' => array('Fiji'),
		'FI' => array('Finland'),
		'FR' => array('France'),
		'GF' => array('French Guiana'),
		'PF' => array('French Polynesia'),
		'TF' => array('French Southern Territories'),
		'GA' => array('Gabon'),
		'GM' => array('Gambia'),
		'GE' => array('Georgia'),
		'DE' => array('Germany', 'Deutschland'),
		'GH' => array('Ghana'),
		'GI' => array('Gibraltar'),
		'GR' => array('Greece'),
		'GL' => array('Greenland'),
		'GD' => array('Grenada'),
		'GP' => array('Guadeloupe'),
		'GU' => array('Guam'),
		'GT' => array('Guatemala'),
		'GN' => array('Guinea'),
		'GW' => array('Guinea-Bissau'),
		'GY' => array('Guyana'),
		'HT' => array('Haiti'),
		'HM' => array('Heard Island and Mcdonald Islands'),
		'VA' => array('Holy See (Vatican City State)'),
		'HN' => array('Honduras'),
		'HK' => array('Hong Kong'),
		'HU' => array('Hungary'),
		'IS' => array('Iceland'),
		'IN' => array('India'),
		'ID' => array('Indonesia'),
		'IR' => array('Iran, Islamic Republic of'),
		'IQ' => array('Iraq'),
		'IE' => array('Ireland'),
		'IL' => array('Israel'),
		'IT' => array('Italy'),
		'JM' => array('Jamaica'),
		'JP' => array('Japan'),
		'JO' => array('Jordan'),
		'KZ' => array('Kazakhstan'),
		'KE' => array('Kenya'),
		'KI' => array('Kiribati'),
		'KP' => array('Korea, Democratic People\'s Republic of'),
		'KR' => array('Korea, Republic of'),
		'KW' => array('Kuwait'),
		'KG' => array('Kyrgyzstan'),
		'LA' => array('Lao People\'s Democratic Republic'),
		'LV' => array('Latvia', 'Republic of Latvia'),
		'LB' => array('Lebanon'),
		'LS' => array('Lesotho'),
		'LR' => array('Liberia'),
		'LY' => array('Libyan Arab Jamahiriya'),
		'LI' => array('Liechtenstein'),
		'LT' => array('Lithuania'),
		'LU' => array('Luxembourg'),
		'MO' => array('Macao', 'Macau'),
		'MK' => array('Macedonia, the Former Yugoslav Republic of', 'Macedonia'),
		'MG' => array('Madagascar'),
		'MW' => array('Malawi'),
		'MY' => array('Malaysia'),
		'MV' => array('Maldives'),
		'ML' => array('Mali'),
		'MT' => array('Malta'),
		'MH' => array('Marshall Islands'),
		'MQ' => array('Martinique'),
		'MR' => array('Mauritania'),
		'MU' => array('Mauritius'),
		'YT' => array('Mayotte'),
		'MX' => array('Mexico'),
		'FM' => array('Micronesia, Federated States of'),
		'MD' => array('Moldova, Republic of'),
		'MC' => array('Monaco'),
		'MN' => array('Mongolia'),
		'MS' => array('Montserrat'),
		'MA' => array('Morocco'),
		'MZ' => array('Mozambique'),
		'MM' => array('Myanmar'),
		'NA' => array('Namibia'),
		'NR' => array('Nauru'),
		'NP' => array('Nepal'),
		'NL' => array('Netherlands', 'The Netherlands'),
		'AN' => array('Netherlands Antilles'),
		'NC' => array('New Caledonia'),
		'NZ' => array('New Zealand'),
		'NI' => array('Nicaragua'),
		'NE' => array('Niger'),
		'NG' => array('Nigeria'),
		'NU' => array('Niue'),
		'NF' => array('Norfolk Island'),
		'MP' => array('Northern Mariana Islands'),
		'NO' => array('Norway'),
		'OM' => array('Oman'),
		'PK' => array('Pakistan'),
		'PW' => array('Palau'),
		'PS' => array('Palestinian Territory, Occupied'),
		'PA' => array('Panama'),
		'PG' => array('Papua New Guinea'),
		'PY' => array('Paraguay'),
		'PE' => array('Peru'),
		'PH' => array('Philippines'),
		'PN' => array('Pitcairn'),
		'PL' => array('Poland'),
		'PT' => array('Portugal'),
		'PR' => array('Puerto Rico'),
		'QA' => array('Qatar'),
		'RE' => array('Reunion'),
		'RO' => array('Romania'),
		'RU' => array('Russian Federation', 'Russia'),
		'RW' => array('Rwanda'),
		'SH' => array('Saint Helena'),
		'KN' => array('Saint Kitts and Nevis'),
		'LC' => array('Saint Lucia'),
		'PM' => array('Saint Pierre and Miquelon'),
		'VC' => array('Saint Vincent and the Grenadines'),
		'WS' => array('Samoa'),
		'SM' => array('San Marino'),
		'ST' => array('Sao Tome and Principe'),
		'SA' => array('Saudi Arabia'),
		'SN' => array('Senegal'),
		'CS' => array('Serbia and Montenegro', 'Serbia'),
		'SC' => array('Seychelles'),
		'SL' => array('Sierra Leone'),
		'SG' => array('Singapore'),
		'SK' => array('Slovakia'),
		'SI' => array('Slovenia'),
		'SB' => array('Solomon Islands'),
		'SO' => array('Somalia'),
		'ZA' => array('South Africa'),
		'GS' => array('South Georgia and the South Sandwich Islands'),
		'ES' => array('Spain'),
		'LK' => array('Sri Lanka'),
		'SD' => array('Sudan'),
		'SR' => array('Suriname'),
		'SJ' => array('Svalbard and Jan Mayen'),
		'SZ' => array('Swaziland'),
		'SE' => array('Sweden'),
		'CH' => array('Switzerland'),
		'SY' => array('Syrian Arab Republic'),
		'TW' => array('Taiwan'),
		'TJ' => array('Tajikistan'),
		'TZ' => array('Tanzania, United Republic of'),
		'TH' => array('Thailand'),
		'TL' => array('Timor-Leste'),
		'TG' => array('Togo'),
		'TK' => array('Tokelau'),
		'TO' => array('Tonga'),
		'TT' => array('Trinidad and Tobago'),
		'TN' => array('Tunisia'),
		'TR' => array('Turkey'),
		'TM' => array('Turkmenistan'),
		'TC' => array('Turks and Caicos Islands'),
		'TV' => array('Tuvalu'),
		'UG' => array('Uganda'),
		'UA' => array('Ukraine'),
		'AE' => array('United Arab Emirates'),
		'GB' => array('United Kingdom', 'UK', 'England'),
		'US' => array('United States', 'US', 'USA'),
		'UM' => array('United States Minor Outlying Islands'),
		'UY' => array('Uruguay'),
		'UZ' => array('Uzbekistan'),
		'VU' => array('Vanuatu'),
		'VE' => array('Venezuela'),
		'VN' => array('Viet Nam', 'Vietnam'),
		'VG' => array('Virgin Islands, British'),
		'VI' => array('Virgin Islands, U.s.'),
		'WF' => array('Wallis and Futuna'),
		'EH' => array('Western Sahara'),
		'YE' => array('Yemen'),
		'ZM' => array('Zambia'),
		'ZW' => array('Zimbabwe'),
	);

	static private $usStates_ = array(
		'AL'=>"Alabama",  
		'AK'=>"Alaska",  
		'AZ'=>"Arizona",  
		'AR'=>"Arkansas",  
		'CA'=>"California",  
		'CO'=>"Colorado",  
		'CT'=>"Connecticut",  
		'DE'=>"Delaware",  
		'DC'=>"District Of Columbia",  
		'FL'=>"Florida",  
		'GA'=>"Georgia",  
		'HI'=>"Hawaii",  
		'ID'=>"Idaho",  
		'IL'=>"Illinois",  
		'IN'=>"Indiana",  
		'IA'=>"Iowa",  
		'KS'=>"Kansas",  
		'KY'=>"Kentucky",  
		'LA'=>"Louisiana",  
		'ME'=>"Maine",  
		'MD'=>"Maryland",  
		'MA'=>"Massachusetts",  
		'MI'=>"Michigan",  
		'MN'=>"Minnesota",  
		'MS'=>"Mississippi",  
		'MO'=>"Missouri",  
		'MT'=>"Montana",
		'NE'=>"Nebraska",
		'NV'=>"Nevada",
		'NH'=>"New Hampshire",
		'NJ'=>"New Jersey",
		'NM'=>"New Mexico",
		'NY'=>"New York",
		'NC'=>"North Carolina",
		'ND'=>"North Dakota",
		'OH'=>"Ohio",  
		'OK'=>"Oklahoma",  
		'OR'=>"Oregon",  
		'PA'=>"Pennsylvania",  
		'RI'=>"Rhode Island",  
		'SC'=>"South Carolina",  
		'SD'=>"South Dakota",
		'TN'=>"Tennessee",  
		'TX'=>"Texas",  
		'UT'=>"Utah",  
		'VT'=>"Vermont",  
		'VA'=>"Virginia",  
		'WA'=>"Washington",  
		'WV'=>"West Virginia",  
		'WI'=>"Wisconsin",  
		'WY'=>"Wyoming"
	);

	static public function guessCountry($location) {
		$s = explode(',', $location);
		$s = strtolower(trim($s[count($s) - 1]));

		foreach (self::$countries_ as $code => $countries) {
			foreach ($countries as $c) {
				if ($s == strtolower($c)) {
					return $code;
				}
			}
		}

		foreach (self::$usStates_ as $code => $state) {
			if ($code == strtoupper($s)) {
				return 'US';
			}
			if (strtolower($state) == strtolower($s)) {
				return 'US';
			}
		}

		// Check country code

		return null;

		//throw new Exception('Cannot find for country for location: ' : $location);
	}

}